export const SEARCH_RECIPES = "search_recipes";
export const SAVE_SEARCH_TERM = "save_search_term";
export const FETCH_SEARCH_TERM = "fetch_search_term";
export const FETCH_RECIPES = "fetch_recipes";
export const IS_LOADING_RECIPES = "is_loading_recipes";
export const IS_LOADING_RECIPE = "is_loading_recipe";
export const FETCH_RECIPE = "fetch_recipe";
export const RECIPES_SEARCH_ERROR = "recipes_search_error";
export const RECIPE_ERROR = "recipe_error";
export const LIKE_RECIPE = "like_recipe";
export const ADD_TO_SHOPPING_LIST = "add_to_shopping_list";
export const CREATE_SHOPPING_LIST = "create_shopping_list";
export const SHOPPING_LIST_ERROR = "shopping_list_error";
// export const UPDATE_SHOPPING_LIST = 'update_shopping_list'
export const FETCH_SHOPPING_LIST = "fetch_shopping_list";
export const IS_LOADING_SHOPPING_LIST = "is_loading_shopping_list";
export const CHANGE_SERVINGS = "change_servings";
export const SIGN_UP = "sign_up";
export const AUTH_ERROR = "auth_error";
export const REQUEST_RESET = "request_reset";
// export const RESET_PASSWORD = "reset_password";
export const FETCH_USER = "fetch_user";
export const FETCH_FAV_RECIPES = "fetch_fav_recipes";
export const FETCH_TOTAL_FAV_RECIPES = "fetch_total_fav_recipes"
